# Generated by Django 3.0.11 on 2021-01-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_or_volume_measurement', models.CharField(choices=[('VL', 'Volume'), ('MS', 'Mass')], default='MS', max_length=2)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('unit_of_measurement', models.CharField(choices=[('OZ', 'Ounces'), ('LBS', 'Pounds'), ('GR', 'Grams'), ('FLOZ', 'Fluid Ounces')], default='GR', max_length=4)),
                ('serving_size', models.IntegerField()),
                ('fat_per_serving', models.PositiveIntegerField(default=0)),
                ('carbohydrates_per_serving', models.PositiveIntegerField(default=0)),
                ('protein_per_serving', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quantity', to='recipes.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('ingredient', models.ManyToManyField(related_name='recipes', through='recipes.IngredientQuantity', to='recipes.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quantity', to='recipes.Recipe'),
        ),
    ]
