# Generated by Django 3.0.11 on 2021-01-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210109_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrates_per_serving',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_per_serving',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_per_serving',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
