# Generated by Django 3.0.11 on 2021-01-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210109_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='serving_size',
            new_name='number_of_servings',
        ),
    ]
