# Generated by Django 3.0.11 on 2021-01-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210109_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='number_of_servings',
            new_name='units_per',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(choices=[('OZ', 'Ounces'), ('LBS', 'Pounds'), ('GR', 'Grams'), ('FLOZ', 'Fluid Ounces'), ('CUPS', 'Cups'), ('TBLSPN', 'Table Spoons')], default='GR', max_length=10),
        ),
    ]
