# Generated by Django 3.1.4 on 2020-12-29 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_or_volume_measurement', models.CharField(choices=[('VL', 'Volume'), ('MS', 'Mass')], default='MS', max_length=2)),
                ('unit_of_measurement', models.CharField(choices=[('OZ', 'Ounces'), ('LBS', 'Pounds'), ('GR', 'GR'), ('FLOZ', 'Fluid Ounces')], default='GR', max_length=4)),
                ('recipe_ingredients_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipeingredients')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipe_ingredients_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipeingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('recipe_ingredients_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipeingredients')),
            ],
        ),
    ]
