# Generated by Django 3.1.4 on 2020-12-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrates_per_serving',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_per_serving',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_per_serving',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
